default:
    @just --list

# Set the last `sanctuary` generation to active.
set-sanctuary:
    @just _set-sysconf
    sudo nixos-rebuild switch --flake /etc/nixos/#sanctuary

# Set the last `minimalist` generation to active.
set-minimalist:
    @just _set-sysconf
    sudo nixos-rebuild switch --flake /etc/nixos/#minimalist

# Set the last home-manager generation to active.
set-hman:
    @just _set-homeconf
    home-manager switch

check:
    @just _set-sysconf
    nix flake check /etc/nixos#

# Allows /etc/nixos to joaozinho... Once in a life of a partition.
allow:
    sudo chown joaozinho /etc/nixos

_set-sysconf:
    #!/usr/bin/env bash
    cp /etc/nixos/hardware-configuration.nix .
    rm -rf /etc/nixos/*
    cp *.nix /etc/nixos/
    cp flake.lock /etc/nixos/

_set-homeconf:
    #!/usr/bin/env bash
    rm -rf ~/.config/home-manager
    mkdir ~/.config/home-manager
    cp -r home.nix ~/.config/home-manager/